### ISSUE TITLE
Melhorias no css

### ISSUE THREAD

**Issue by ohthias** [PedroVazN/V3RSE#1]
### Olá, Pedro! Como vai?

Criei este _issue_ para mostrar as possíveis melhorias que podem ser feitas em seus códigos CSS. Estive revisando-os e observei que há espaço para melhorias não apenas na aparência, mas também na responsividade.

**Comment by PedroVazN** [comment]
Olá Matheus, agradeço desde já, com certeza irei analisar as suas melhorias e adptar ao meu projeto.

**Comment by ohthias** [comment]
Fiz várias melhorias em grande parte do seu código, pois em algumas partes a sintaxe não fazia sentido e poderia ser aprimorada.

As melhorias foram:

**CSS**

- Criação de um único arquivo root para o CSS.
- Adição de responsividade ao design.
- Implementação de um header de navegação.
- Realocação dos filmes favoritos.
- Aprimoramento da interface dos 'cards'.
- Aperfeiçoamento da barra de busca.
- Melhoria no design da página principal ('index').
- Implementação de uma paleta de cores consistente.
- Uso de uma única fonte no projeto com diferentes tamanhos e espessuras.

**JS**

- Adição de redirecionamento para a seção de busca através da navegação no cabeçalho.
- Inclusão de um pre-set padrão quando a barra de busca está vazia.
- Adição de classes a elementos que são gerados dinamicamente.
- Aumento do número de filmes exibidos.
- Atualização da barra de busca para carregar os resultados enquanto o usuário digita, em vez de exigir um botão de busca.

**Outros**

- Organização das pastas de imagens e dos arquivos HTML utilizados no projeto.
- Renomeação de arquivos para uma estrutura mais clara.
- Exclusão de arquivos desnecessários.
- Padronização da cor dos ícones SVG.

Aqui  está a versão com as melhorias ^^

> [V3RSE-V2.zip](https://github.com/PedroVazN/V3RSE/files/12570606/V3RSE-V2.zip)



Se você pretende fazer alterações, recomendo que crie um novo branch e faça um pull-request. Isso garantirá que seus arquivos atuais permaneçam intocados e permitirá um controle preciso das modificações no projeto. Além disso, é importante manter um controle de versão do projeto para uma gestão eficaz das mudanças.

Qualquer coisa pode chamar ^^
